################################# Default configuration ###################
baseURL = "https://www.robitec.es"
title = "Robitec"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"

# disable language
disableLanguages = ['en', 'fr']
defaultContentLanguage = 'es'

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "Nosotros"
pre = "#"
url = "about"
weight = 1

[[menu.main]]
name = "Servicios"
pre = "#"
url = "services"
weight = 2

# [[menu.main]]
# name = "portfolio"
# pre = "#"
# url = "portfolio"
# weight = 3

# [[menu.main]]
# name = "team"
# pre = "#"
# url = "team"
# weight = 4

[[menu.main]]
# name = "pricing"
# pre = "#"
# url = "pricing"
# weight = 5

[[menu.main]]
name = "Empresa"
# pre = "#"
url = "team"
weight = 6

[[menu.main]]
name = "Contacto"
pre = "#"
url = "contact"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = ""
author = ""
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

[params.footer]
logo = "images/grup_mauri.svg"
link = "https://www.bmauri.com"

# preloader
[params.preloader]
enable = false
preloader = "images/logo.svg"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/robitec-industry-solutions/"



################################ Spanish Language ########################

[Languages.es]
languageName = "Es"
languageCode = "es"
contentDir = "content/spanish"
weight = 1
home = "Inicio"
copyright = "Copyright &copy; 2020 Designed by Themefisher"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
